movieproject/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movielist/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.addmovie,name='addmovie'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django . urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.

class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')



    def __str__(self):
        return self.name


movieproject/movieapp/forms.py
from django import forms
from . models import Movies

class Movieform(forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from movieapp.forms import Movieform
from movieapp.models import Movies


# Create your views here.
def index(request):
    movie=Movies.objects.all()
    context={
        'movielist':movie
    }
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def addmovie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES.get('img')
        movie=Movies(name=name,desc=desc,year=year,img=img)
        movie.save();
        return redirect('/')
    return render(request,'add.html')

def delete(request,id):
    if request.method=='POST':
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    movie=Movies.objects.get(id=id)
    form=Movieform(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'movie':movie})

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   NAME  : <input type="text" name="name">
   DESC  : <input type="text" name="desc">
   YEAR  : <input type="number" name="year">
   IMAGE : <input type="file" name="img">
   <br>
   <br>
    <input type="submit">
</form>

</body>
</html>
{% endblock %}

movieproject/templates/base.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">MOVIES</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link active" href="{% url 'movieapp:addmovie'  %}">ADD MOVIE</a>

    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}

    ARE YOU WANT TO DELETE THIS PAGE ?

    <input type="submit">

</form>
</body>
</html>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
<div class="container">
    <div class="shadow card">
        <center>
        <h2>{{ movie.name }}</h2>
        <img src="{{ movie.img.url }}" height="300" width="600"><br>
{{ movie.name }}<br>
{{ movie.desc }}<br>
{{ movie.year }}<br>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
            <a class="btn btn-info" href="{% url 'movieapp:update' movie.id %}">update</a>
    </div>
</div>
</center>
{% endblock %}
</body>
</html>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div align="left">
<!--<a class="btn btn-primary"  href="{% url 'movieapp:addmovie'  %}">ADD MOVIE</a>-->
</div>
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        {% for i in movielist %}
        <div class="shadow card" width="300" height="250">
       <div class="col-sm-auto">
          <center><h6> {{ i.name}}</h6></center>
          <center><img src="{{ i.img.url }}" height="250" width="250"></center>

          <center> <a class="btn btn-info" href="{% url 'movieapp:detail' i.id %}">About</a></center>
       </div>
            </div>
         {% endfor %}
    </div>
    </div>
</di

{% endblock %}



movieproject/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit">

</form>
</body>
</html>